name: 'Install Tippecanoe'
description: 'Install tippecanoe into workflow`s environment'
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: tippecanoe.sh
      shell: bash