name: Generate vectortiles from source data

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tippecanoe
        run: bash ./.github/actions/install-tippecanoe/tippecanoe.sh