name: Generate vectortiles from source data

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello world!"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tippecanoe
        uses: ./.github/actions/install-tippecanoe